# Generated by Django 4.2.30 on 2026-06-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_v32_lite_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='stocks.themegroup')),
            ],
            options={
                'ordering': ('group__sort_order', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StockTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_links', to='stocks.stock')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_links', to='stocks.theme')),
            ],
            options={
                'ordering': ('stock_id', 'theme__group__sort_order', 'theme__sort_order'),
            },
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_theme_group_name'),
        ),
        migrations.AddIndex(
            model_name='stocktheme',
            index=models.Index(fields=['is_primary'], name='stocks_stoc_is_prim_ca7b6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktheme',
            constraint=models.UniqueConstraint(fields=('stock', 'theme'), name='unique_stock_theme'),
        ),
    ]
