# Generated by Django 4.2.30 on 2026-05-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WALKING', 'Walking'), ('CYCLING', 'Cycling'), ('HIKING', 'Hiking'), ('FITNESS_SPOT', 'Fitness Spot')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=40)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('distance_km', models.FloatField(default=0)),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10)),
                ('cycle_type', models.CharField(blank=True, max_length=40)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('start_lat', models.FloatField(db_index=True)),
                ('start_lng', models.FloatField(db_index=True)),
                ('gpx_simplified', models.JSONField(blank=True, default=list)),
                ('gpx_original_url', models.URLField(blank=True)),
                ('source', models.CharField(max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('avg_rating', models.FloatField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('nearby_parking', models.TextField(blank=True, null=True)),
                ('nearby_transit', models.TextField(blank=True, null=True)),
                ('traveler_info', models.TextField(blank=True, null=True)),
                ('toilet_info', models.TextField(blank=True, null=True)),
                ('convenience_info', models.TextField(blank=True, null=True)),
                ('accessibility_sources', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FitnessSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_types', models.JSONField(blank=True, default=list)),
                ('lat', models.FloatField(db_index=True)),
                ('lng', models.FloatField(db_index=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='PUBLIC_DATA', max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('avg_rating', models.FloatField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitness_spots', to='catalog.category')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['lat', 'lng'], name='catalog_fit_lat_018280_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fitnessspot',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_spot_source_external_id'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['start_lat', 'start_lng'], name='catalog_cou_start_l_b16a00_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'difficulty', 'region'], name='catalog_cou_categor_66a117_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_course_source_external_id'),
        ),
    ]
